# Generated by Django 3.2.4 on 2021-06-30 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DateOfCreating',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 6, 30, 15, 8, 35, 261829, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
